FROM node:20-alpine

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Disable Angular analytics prompt
ENV NG_CLI_ANALYTICS=false

EXPOSE 4200

CMD ["npm", "start", "--", "--host", "0.0.0.0", "--poll"]
