apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-web
  template:
    metadata:
      labels:
        app: frontend-web
    spec:
      containers:
        - name: frontend-container
          image: us-central1-docker.pkg.dev/medisupply-474421/medisupply/frontend-web:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: frontend-backend-config
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    requestPath: "/health"
    type: HTTP
    port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-web-service
  namespace: default
  annotations:
    cloud.google.com/backend-config: '{"default": "frontend-backend-config"}'
spec:
  type: NodePort
  selector:
    app: frontend-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30015
